### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by damassi**

### CODE REVIEW

**Comment by hudakdidit** [comment]
@damassi 
Ha, thanks! Do you use CJSX?

**Comment by damassi** [comment]
@hudakdidit - I used to, but then Babel.js hit the scene and there's absolutely no looking back.  What's happening over in ES6 / ES7 land is not to be missed!   

I love this image from Dan Abramov; it really captures where the language is going: 
cc1akxwumaaz23l

**Comment by hudakdidit** [comment]
@damassi rad! Yes recently used react-dnd on a project and used es6/7 for some components. Do you have any public repos that demonstrate using es6 I could check out?

**Comment by damassi** [comment]
Ah, nothing public unfortunately, but we're using it all over Kindling :)  Webpack + Babel Loader = woww

**Pull request merged**
